INSERT INTO "public"."tiktok_stats" (artist_id, username, followers_count, profile_link) VALUES
(3 ,'matisse_mx', 1087923, 'https://www.tiktok.com/@matisse_mx'),
(2 ,'espinozapaz', 2545616, 'https://www.tiktok.com/@espinozapaz'),
(4,'juansalazarjs', 156533, 'https://www.tiktok.com/@juansalazarjs'),
( 6,'tierrablanca_angel', 7894, 'https://www.tiktok.com/@tierrablanca_angel'),
( 8,'canoaguilaroficial1', 16220, 'https://www.tiktok.com/@canoaguilaroficial1'),
( 7,'teoydiego', 1517, 'https://www.tiktok.com/@teoydiego'),
( 12,'christiannodal', 2154024, 'https://www.tiktok.com/@christiannodal'),
( 11,'carolinarossmusic', 2857307, 'https://www.tiktok.com/@carolinarossmusic'),
( 13,'jossfavela', 471035, 'https://www.tiktok.com/@jossfavela'),
( 16, 'loshhoficial', 11025, 'https://www.tiktok.com/@loshhoficial'),
( 14, 'angelaaguilar_', 12809620, 'https://www.tiktok.com/@angelaaguilar_'),
( 18, 'talentolideroficial', 1015168, 'https://www.tiktok.com/@talentolideroficial'),
( 19, 'manumedinaofficial', 7059, 'https://www.tiktok.com/@manumedinaofficial'),
( 20, 'gaelcardona01', 29934, 'https://www.tiktok.com/@gaelcardona01'),
( 23, 'hugocoroneloficial', 1718, 'https://www.tiktok.com/@hugocoroneloficial'),
( 25, 'latinpowermusic', 4681, 'https://www.tiktok.com/@latinpowermusic'),
(24 , 'grupohistoriaofficial', 72857, 'https://www.tiktok.com/@grupohistoriaofficial'),
( 26, 'katiaofficial', 25888, 'https://www.tiktok.com/@katiaofficial'),
( 28, 'laejecutivaoficial', 143141, 'https://www.tiktok.com/@laejecutivaoficial'),
( 27, 'ivanciniflores', 762692, 'https://www.tiktok.com/@ivanciniflores'),
--1, , 'mprecordsmx', 130701, 'https://www.tiktok.com/@mprecordsmx'),
(30, 'santosguzmanoficial', 1220, 'https://www.tiktok.com/@santosguzmanoficial'),
( 31, 'platasoficial', 97906, 'https://www.tiktok.com/@platasoficial'),
( 32, 'kevinmelendresoriginal', 22856, 'https://www.tiktok.com/@kevinmelendresoriginal'),
(35, 'cristianjacobooficial', 43197, 'https://www.tiktok.com/@cristianjacobooficial'),
(46 , 'bandamachos_', 7405, 'https://www.tiktok.com/@bandamachos_'),
(52 , 'eduincaz5', 8311675, 'https://www.tiktok.com/@eduincaz5'),
( 54, 'andreanunez_mx', 55537, 'https://www.tiktok.com/@andreanunez_mx'),
( 56, 'banda_ms', 4080694, 'https://www.tiktok.com/@banda_ms'),
( 57, 'javierlarranagaofficial', 437034, 'https://www.tiktok.com/@javierlarranagaofficial'),
( 61, 'anabarbaraoficial', 8897353, 'https://www.tiktok.com/@anabarbaraoficial'),
( 62, 'larrymania', 6938332, 'https://www.tiktok.com/@larrymania'),
( 63, 'ulisesronces', 3311183, 'https://www.tiktok.com/@ulisesronces'),
( 64, 'gallo_elizalde', 174232, 'https://www.tiktok.com/@gallo_elizalde'),
( 67, 'grupofirme', 5557634, 'https://www.tiktok.com/@grupofirme');